### ISSUE TITLE
Player having Windows 8 issues

### ISSUE THREAD

**Issue by travislbrundage** [ConfirmedMel/DestinyAccounts#46]
https://mapledestiny.net/forum/threads/9058/

He's getting two errors.
1) Error code : - 2005530585 (Unknown error 0x88760827) http://i.imgur.com/lEFfd05.jpg?1
2) Error code : -2147467259 (Unspecified error) http://i.imgur.com/FIXnBs4.jpg?1

Awaiting player response.

**Comment by ConfirmedMel** [comment]
Player hasn't responded in over two weeks. Considered solved.
