### ISSUE TITLE
End Game RMTer

### ISSUE THREAD

**Issue by Neliobelmont** [ConfirmedMel/DestinyAccounts#51]
Two players (Sora & Susan) have reported that a person has tried to sell them end game items.  They were contacted by mule accounts IGN: Archer93 and IGN: draenor.  Draenor was on IP: 216.169.110.212 though they are likely using a proxy.

Fayzon was able to provide the following SS to me.
http://puu.sh/e0UmD/c1c9409aca.jpg

Some of the items being sold are:
31 atk 11 dex Yellow Snow Shoes (ID: 1072239)
30 atk Brown Work Glove (ID: 1082149)
80 Luk Black Gar (ID: 1052072)
29 atk Cape

These items are being sold for over $100 each, and this needs to be shut down.  Please try and track the Mac addressed of those two accounts, and hopefully find the person selling.  If you are unable to find the exact player, please look for a mule account with these items stashed on it.  It's likely they have sold their main account now selling items separately.

I also believe this may be the player Annabelle (recently renamed Nightlock).

**Comment by Neliobelmont** [comment]
Screen Shots of part of the conversation I had with Susan.
http://puu.sh/e0Vtn/be91f58b6a.jpg
http://puu.sh/e0Vz5/2f2cf8f9c3.jpg

I thought I had taken more, but apparently when I did my first SS, my maple client crashed.

**Comment by ConfirmedMel** [comment]
Banned ACCID 65259 // bouzin123 - 
No sign of a YSS with that attack, however this account is stocked with tons of high level godly gear (end game items) including 2 different black gara, 3 attack shoes, stormcaster gloves, 30 att bwgs, 2 29 att PAC, and a 33 att PGC.

Mac address can not be linked to any other account, nor any IPs. This guy must have used a completely new computer / router to set this whole thing up. Account has only been logged into 4 times in one day, on the 2nd of January (also the create date). 

I can not link this account to annabelle. 
I can not link this account to either of the mule accounts, nor can I link the mule accounts to annabelle. 

The best I can do is ban the mule account that I found.

**Comment by Neliobelmont** [comment]
Okay.  I guess we will see who come crawling to us asking why their account was banned.
