### ISSUE TITLE
Player NPC Text Removal - SkyzBM

### ISSUE THREAD

**Issue by Neliobelmont** [ConfirmedMel/DestinyAccounts#52]
Recently SkyzBM purchased a NPC.  The text for the NPC "I have reached level 200" is still displaying on the map and needs to be removed.

IGN: SkyzBM
Map: 103000000
Script: 9901245
Pos: 1743x -144y

**Comment by ConfirmedMel** [comment]
That text disappears after a server restart. 

Thanks!
