### ISSUE TITLE
NX / AP Reset Wipes from a few Second Chances.

### ISSUE THREAD

**Issue by Neliobelmont** [ConfirmedMel/DestinyAccounts#53]
I need you to remove all NX and AP Resets (ID: 5050000) from the following Accounts:

spirit296
spirit297
theways00
Suprema15

IGN: iLancelot

These players have promised not to engage in this again, and I'll be keeping an eye on them as usual.

**Comment by ConfirmedMel** [comment]
None of the accounts had AP resets.
Removed all NX from each account.
